$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1442822560592.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9cf129c72a0d4e65a83780252a554acb",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c763d9919a042f3bfce9cf29213551b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":130},
            "size":{
              "width":85,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7380df0af24977b13449efce18e0d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":130},
                "size":{
                  "width":85,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "4c763d9919a042f3bfce9cf29213551b":{
      "scriptId":"u0"},
    "ab7380df0af24977b13449efce18e0d7":{
      "scriptId":"u1"}}});